### ISSUE TITLE
Failed to request device code device_flow_disabled

### ISSUE THREAD

**Issue by larsks** [hubtty/hubtty#83]
After installing `hubtty` and the minimal configuration, running `hubtty` results in:

```
Failed to request device code device_flow_disabled: Device Flow must be explicitly enabled for this App
```

I'm not sure what to do with this error message. Is that telling me that *I* need to change a setting in my github account?

**Comment by mandre** [comment]
Hi @larsks, I noticed this as well last week and enabled the device flow in the hubtty application page. This appears to be a new setting that wasn't previously required. Sorry for the trouble, please give it another try and let me know if it works for you now.

**Comment by mandre** [comment]
Yes, this is what was missing. More details at https://github.blog/changelog/2022-03-16-enable-oauth-device-authentication-flow-for-apps/
